export default [
  {
    id: 1,
    name: 'Pomodoro',
    url: 'https://celeste6666.github.io/pomodoro/view/index.html',
    sourceCode: 'https://github.com/Celeste6666/pomodoro',
    type: 'Web',
    skill: ['js', 'Firebase'],
    picture: './pomodoro.png',
    pictureAlt: '',
  },
  {
    id: 2,
    name: 'Vue 網站作品集',
    url: '',
    sourceCode: 'https://celeste6666.github.io/vue_portfolio/',
    type: 'Web',
    skill: ['Vue.js', 'Vue-Router', 'Vuex', 'Vuetify'],
    picture: './portfolio.png',
    pictureAlt: '',
  },
  {
    id: 3,
    name: 'Vue 玩具電商',
    url: 'https://celeste6666.github.io/toystore/',
    sourceCode: 'https://github.com/Celeste6666/toystore',
    type: 'E-Commerce',
    skill: ['Vue.js', 'Vue-Router', 'Vuex', 'ES6', 'Firebase', 'scss', 'Bootstrap'],
    picture: './toyStore.png',
    pictureAlt: '',
  },
  {
    id: 4,
    name: 'Vue 全台公車動態時刻查詢應用服務',
    url: 'https://celeste6666.github.io/DynamicBusRoute/',
    sourceCode: 'https://github.com/Celeste6666/DynamicBusRoute',
    type: 'Mobile',
    skill: ['Vue.js', 'Vue-Router', 'Vuex', 'ES6', 'scss', 'Bootstrap'],
    picture: './DynamicBusRoute.png',
    pictureAlt: '',
  },
  {
    id: 5,
    name: 'RWD_寵物友善商店',
    url: 'https://celeste6666.github.io/rwd_project/PetCare/dist/home.html',
    sourceCode: 'https://github.com/Celeste6666/rwd_project/tree/main/PetCare',
    type: 'Web',
    skill: ['html', 'scss', 'js'],
    picture: './rwd_petcare.png',
    pictureAlt: '',
  },
];
