export default [
  {
    id: 1,
    name: 'Pomodoro',
    url: 'https://celeste6666.github.io/pomodoro/view/index.html',
    sourceCode: 'https://github.com/Celeste6666/pomodoro',
    type: 'Web',
    skill: ['js', 'Firebase'],
    picture: './pomodoro.png',
    pictureAlt: '',
  },
  {
    id: 2,
    name: '網站作品集',
    url: '',
    sourceCode: 'https://celeste6666.github.io/vue_portfolio/',
    type: 'Web',
    skill: ['Vue.js', 'Vue Router', 'Vuex', 'Vuetify'],
    picture: './portfolio.png',
    pictureAlt: '',
  },
  {
    id: 3,
    name: '玩具電商',
    url: 'https://celeste6666.github.io/toystore/',
    sourceCode: 'https://github.com/Celeste6666/toystore',
    type: 'E-Commerce',
    skill: ['Vue.js', 'Vue Router', 'Vuex', 'ES6', 'scss', 'Firebase'],
    picture: './toyStore.png',
    pictureAlt: '',
  },
  {
    id: 4,
    name: '全台公車動態時刻查詢應用服務',
    url: 'https://celeste6666.github.io/DynamicBusRoute/',
    sourceCode: 'https://github.com/Celeste6666/DynamicBusRoute',
    type: 'Mobile',
    skill: ['Vue.js', 'Vue Router', 'Vuex', 'ES6', 'scss'],
    picture: './DynamicBusRoute.png',
    pictureAlt: '',
  },
  {
    id: 5,
    name: 'React 後臺管理系統',
    url: 'https://celeste6666.github.io/react_admin_client/login',
    sourceCode: 'https://github.com/Celeste6666/react_admin_client',
    type: 'Web',
    skill: ['React', 'Redux', 'React Router', 'ES6', 'antd', 'Firebase'],
    picture: './ReactAdmin.png',
    pictureAlt: '',
  },
  {
    id: 6,
    name: 'Scrum',
    url: 'https://celeste6666.github.io/scrum/',
    sourceCode: 'https://github.com/Celeste6666/scrum/tree/master',
    type: 'Web',
    skill: ['React', 'Redux', 'React Router', 'ES6', 'Tailwind CSS'],
    picture: './scrum.png',
    pictureAlt: '',
  },
];
